### ISSUE TITLE
Enormous CPU usage on the JPEG XL art "test page"

### ISSUE THREAD

**Issue by nekohayo** [zamfofex/jxl-crx#4]
On Firefox 110 (stable) on Fedora 37's Xorg/X11 GNOME session, with open source AMD radeon R7/R9 270 graphics,

with this extension and `image.jxl.enabled` turned on in `about:config`, https://jpegxl.info/art/ works fine, but https://jpegxl.info/test-page/ never manages to load the JPEG XL images, and it uses 100% of my 8 CPU cores, indefinitely. This is also reflected in `about:performance`:

![image](https://user-images.githubusercontent.com/479401/222157416-352e925b-d5fd-4e83-967b-3837e63610d8.png)

**Comment by jonnyawsom3** [comment]
Had the same happen on a cloudinary page, although after a minute the page closed itself due to hitting memory limits so something's very wrong

**Comment by jonsneyers** [comment]
Could it be the animation on that test page that causes trouble?

**Comment by jonnyawsom3** [comment]
It also happens on this page https://cloudinary.com/blog/how_jpeg_xl_compares_to_other_image_codecs where interestingly the first three images fail to load at all without the plugin for me

**Comment by zamfofex** [comment]
Does this happen consistently? Are there errors or messages logged in the console?

**Comment by eylenburg** [comment]
I have the same problem. The JXL picture is not loading, just some flickering where it should be. CPU goes up until the page is closed. No errors in the console. The reload button continues to show "X", as in, the website has not finished loading.

Firefox 113

**Comment by combolek** [comment]
> Does this happen consistently?

Yes, every time. Both Windows and Linux.

> Are there errors or messages logged in the console?

Not that I can see.

**Comment by Crystal-RainSlide** [comment]
@zamfofex I can confirm all the JXL images on https://jpegxl.info/test-page/ are loading again and again on Firefox. And it's related with `srcset`.

Sadly, before I go far enough into this, maybe because Windows is too weak for decoding all these JPEG XL test images repeatly, it give me a blue screen.

To debug this problem without running the code for too long & into blue screen again, I crafted a webpage with only the `<img>` HTML code of the smallest 10 Kb JPEG XL test image:

```
<!DOCTYPE html>
<meta charset="UTF-8">
<img src="https://jpegxl.info/test-page/Webkit-logo-P3.jxl" srcset="https://jpegxl.info/test-page/Webkit-logo-P3.jxl 2x">
```

And it loads repeatly.

Then I removed `srcset`, now the `<img>` looks just like the ones that works on https://jpegxl.info/art/:

```
<!DOCTYPE html>
<meta charset="UTF-8">
<img src="https://jpegxl.info/test-page/Webkit-logo-P3.jxl">
```

And it loads fine.

**Comment by 1div0** [comment]
0 problems w/ CPU load here, F39. Only JPEG XL animation is MIA. OTOH Thorium displays everything except 16-bit per channel colour space.

**Comment by Crystal-RainSlide** [comment]
@1div0 Thorium Browser on Fedora 39?

Since I can reproduce this with Chromium and Vivaldi on Windows, Windows is the biggest suspect now... 🪟

But how?

**Comment by 1div0** [comment]
Th 117.0.5938.157
Fedora Linux 39 β

Windows?
Broken beyond repair. By design.

**Comment by eylenburg** [comment]
> I have the same problem. The JXL picture is not loading, just some flickering where it should be. CPU goes up until the page is closed. No errors in the console. The reload button continues to show "X", as in, the website has not finished loading.
> 
> Firefox 113

It works for me now, Firefox 118 on Windows. Don't know what changed.

**Comment by zznidar** [comment]
I have done some debugging. As mentioned, the `srcset` attribute might be connected to the problems. 
An error event is raised, which is then handled by the `main.js` code https://github.com/zamfofex/jxl-crx/blob/6ec9f6fbef8d21004825f7d78a8060991605de70/main.js#L97-L106
But the function does not return here; rather, it calls `load()` again in the last line.
This creates an endless loop of error -> load -> error -> load ...

However, it is not `main.js` nor `worker.js` that dispatches this error event. My guess is it is thrown by the browser? 

Interestingly, if I add the following line to the beginning of the error event listener mentioned above, it will work (although the images will be around twice the dimensions):
`event.target.removeAttribute("srcset");`

One more observation:
When loading the main page, which loads normally (https://jpegxl.info/), the `MutationObserver` calls the `load()` function. When loading the problematic page (https://jpegxl.info/test-page/), it does not.


The main difference between the main page and the problematic page:
main page:
```html
<picture>
   <source srcset="logo.jxl" type="image/jxl">
   <img src="https://jpegxl.info/fallbacklogo.jpg" alt="JPEG XL logo / browser support test" width="95%">
</picture>
```

problematic page:
```html
<img src="https://jpegxl.info/test-page/red-room.jxl" srcset="red-room.jxl 2x" alt="Red room (jxl)">
```

As you can see, the main page has a `<picture>` element, inside it a `<source>` element with JXL and an `<img>` element (which can either be JXL or JPG – no error will be thrown either way).
The problematic page, however, does not have the `<picture>` element. This probably also explains why the MutationObserver does not call load() in this case.

-----
For testing, I used the latest published release (https://github.com/zamfofex/jxl-crx/releases/tag/v0.2), jxl-mv2.zip

**Comment by zamfofex** [comment]
It listens for an error event from the browser, so if it fails to load an image (in the case the browser doesn’t support JPEG XL), it’ll try to load it using libjxl.

Maybe a simple fix would be to remove the `img.dispatchEvent(...)` from below that snippet you shared. (I added it so people could listen for the `error` event, and if the JPEG XL image failed loaing, it would work as expected.)

Another potential solution (probably preferred) is to check [`event.isTrusted`](https://developer.mozilla.org/en-US/docs/Web/API/Event/isTrusted) on the event listener and return early if it is `false`.

**Comment by Crystal-RainSlide** [comment]
I think I got the final piece of the puzzle, also how to reproduce the problem reliably.

Note that the problem should be fixed in https://github.com/zamfofex/jxl-crx/commit/6ec9f6fbef8d21004825f7d78a8060991605de70, it's just not pushed to the store yet.

### The problem

In version 0.2, for `<img>`s with both `src` and `srcset`, this extension [only changes the `src`](https://github.com/zamfofex/jxl-crx/blob/623593e6431f55e74addd25defa929a69c784293/main.js#L36).

However, when the `src` changes & browsers re-load the images, the browsers may still try to load from `srcset` first anyway.

Thus, the browsers does trigger the error event as guessed before, and cause the loop.

(Even though the changed `src` can actually be loaded without error.)

### Reproduce

- Everyone who can't reproduce this should have a display scale of 1x (100%), and since the `srcset` don't include a `1x` image, the browser don't use the `srcset` after all, and thus everything works fine.
- Vice versa. Mine is 1.5x (150%), if there is one the browser will use a `2x` image from the `srcset` anyway (because the "1x" image from `src` will mostly be blurry for a 1.5x scale), thus I can reproduce it.
- Same as above for everyone else who can also reproduce this.

**Comment by zamfofex** [comment]
@Crystal-RainSlide The issue is still present in the latest version from Git. I decided to take a few minutes to investigate the issue. I’ll push a fix soon, and hopefully release it to the Chrome and Firefox extension/addon stores too.

**Comment by zamfofex** [comment]
I have submitted the new version to the respective web stores, hopefully it should show up soon. If the issue persists, please do let me know, and I can reopen the issue to investigate further!
